# Dependencies
markdown:            kramdown
highlighter:         rouge

# Gems (for Jekyll 3.0)
gems: [jekyll-paginate]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Agrim Mittal
tagline:             'a.k.a hitman'
description:         'Developer . Geek . Hacker'
url:                 http://agrim123.github.io
baseurl:             '/'
paginate:            5

# About/contact
author:
  name:              Agrim Mittal
  url:               https://agrim123.github.io
  email:             agrimmittal97@gmail.com

# Custom vars
version:             2.0

# Social Media
github:       http://github.com/agrim123
disqus:       agrimmittal-me 

# Theme Author (Please don't edit this line cause of MIT LICENSE rules)
theme:
  creator:      Rizky Ariestiyansyah
  codename:     Naringu
  link:         https://github.com/ariestiyansyah/naringu
