# Dependencies
markdown:            kramdown
highlighter:         rouge

# Gems (for Jekyll 3.0)
gems: [jekyll-paginate]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Agrim Mittal
tagline:             'tagline'
description:         'desc'
url:                 http://agrim123.github.io
baseurl:             /
paginate:            7

# About/contact
author:
  name:              Rizky Ariestiyansyah
  url:               https://twitter.com/ariestiyansyah
  email:             ariestiyansyah.rizky@gmail.com

# Custom vars
version:             2.0

# Social Media
github:				http://github.com/agrim123
twitter:			
disqus:        

# Theme Author (Please don't edit this line cause of MIT LICENSE rules)
theme:
  creator:			Rizky Ariestiyansyah
  codename:			Naringu
  link:             https://github.com/ariestiyansyah/naringu
